name: 🚀 Run SMSBoom in Action

# 触发 Action 的条件
on: 
  # 定时触发 参考 https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows#schedule
  # schedule:
  #     - cron: '30 5 * * 1,3'
  #     - cron: '30 5 * * 2,4'
  # 手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 签出项目代码
      - uses: actions/checkout@v3
      # 设置 py3.8 环境
      - name: 🚀 设置Python 3.11环境
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      
      - name: 🚀 安装环境
        # 此处可以自定义命令行运行参数.替换手机号
        run: |
          pip3 install -r requirements.txt
          pip3 install pyinstaller
          echo "ℹ️ [I]环境安装：完成"
      - name: 📦 打包
        run: |
          pyinstaller -F smsboom.py
          echo "ℹ️ [I]打包：完成"
          echo "ℹ️ [I]当前目录:"
          ls
          echo "ℹ️ [I]dist目录:"
          cd dist

